<?php
/** Public catalogue endpoint restricted to explicitly mapped WooCommerce categories. */
if (!defined('ABSPATH')) { exit; }
final class Snapp_Shop_Crawler {
    private const NAMESPACE = 'snappshop/v1'; private const MAX_PER_PAGE = 100;
    public function __construct() { add_action('rest_api_init', [$this, 'routes']); }
    public function routes(): void {
        register_rest_route(self::NAMESPACE, '/products', ['methods' => WP_REST_Server::READABLE, 'callback' => [$this, 'products'], 'permission_callback' => '__return_true', 'args' => ['page' => ['default' => 1, 'sanitize_callback' => 'absint'], 'per_page' => ['default' => self::MAX_PER_PAGE, 'sanitize_callback' => 'absint']]]);
        register_rest_route(self::NAMESPACE, '/products/(?P<product_code>\d+)', ['methods' => WP_REST_Server::READABLE, 'callback' => [$this, 'product'], 'permission_callback' => '__return_true']);
    }
    public function products(WP_REST_Request $request): WP_REST_Response {
        if (!function_exists('wc_get_products')) return new WP_REST_Response(['status' => false, 'message' => 'WooCommerce is required.'], 503); $page = max(1, absint($request['page'])); $per = min(self::MAX_PER_PAGE, max(5, absint($request['per_page']))); $items = $this->eligible_products(); $total = count($items); $slice = array_slice($items, ($page - 1) * $per, $per);
        return new WP_REST_Response(['status' => true, 'data' => ['products' => array_map(fn($product) => ['id' => $product->get_id(), 'code' => $product->get_id(), 'active' => $this->active($product), 'url' => get_permalink($product->get_id())], $slice), 'current_page' => $page, 'per_page' => $per, 'total_items' => $total, 'total_pages' => (int) ceil($total / $per)]]);
    }
    public function product(WP_REST_Request $request) { $product = function_exists('wc_get_product') ? wc_get_product(absint($request['product_code'])) : false; if (!$product || $product->get_status() !== 'publish' || !$this->is_eligible($product)) return new WP_Error('snappshop_product_not_found', 'Product not found.', ['status' => 404]); return new WP_REST_Response(['status' => true, 'data' => $this->details($product)]); }
    private function eligible_products(): array { $ids = Snapp_Shop_Category_Catalogue::mapped_wp_category_ids(); if (!$ids) return []; $products = wc_get_products(['status' => 'publish', 'limit' => -1, 'return' => 'objects']); $products = array_filter($products, fn($product) => $this->is_eligible($product)); usort($products, fn($a, $b) => $this->inclusion_date($b) <=> $this->inclusion_date($a) ?: $a->get_id() <=> $b->get_id()); return $products; }
    private function is_eligible(WC_Product $product): bool { $mapped = Snapp_Shop_Category_Catalogue::mapped_wp_category_ids(); $productCategories = wp_get_post_terms($product->get_id(), 'product_cat', ['fields' => 'ids']); return (bool) array_intersect($mapped, $productCategories) && !in_array(sanitize_title($this->brand($product)), $this->excluded_brands(), true); }
    private function inclusion_date(WC_Product $product): int { $dates = array_map(static fn($id) => Snapp_Shop_Category_Catalogue::inclusion_for_wp_category((int) $id), wp_get_post_terms($product->get_id(), 'product_cat', ['fields' => 'ids'])); return empty($dates) ? 0 : max($dates); }
    private function excluded_brands(): array { $settings = get_option('snapp_shop_order_sync_settings', []); return array_values(array_filter(array_map('sanitize_title', preg_split('/[\r\n,]+/', (string) ($settings['excluded_brands'] ?? ''))))); }
    private function details(WC_Product $product): array { $ids = $product->get_gallery_image_ids(); array_unshift($ids, $product->get_image_id()); $variations = []; if ($product->is_type('variable')) foreach ($product->get_children() as $id) { $variation = wc_get_product($id); if (!$variation instanceof WC_Product_Variation) continue; $image = $variation->get_image_id(); if ($image) $ids[] = $image; $variations[] = ['id' => $variation->get_id(), 'active' => $this->active($variation), 'specs' => $this->variation_specs($variation), 'medias' => $image ? ['image-' . $image] : []]; } $medias = []; foreach (array_unique(array_filter(array_map('absint', $ids))) as $id) { $url = wp_get_attachment_image_url($id, 'full'); if ($url) $medias[] = ['code' => 'image-' . $id, 'type' => 'image', 'url' => $url]; } $image = $product->get_image_id(); return ['id' => $product->get_id(), 'code' => $product->get_id(), 'title' => wp_strip_all_tags($product->get_name()), 'description' => wp_strip_all_tags($product->get_description() ?: $product->get_short_description()), 'specs' => $this->specs($product), 'category' => $this->category($product), 'brand' => $this->brand($product), 'active' => $this->active($product), 'is_fake' => false, 'variations' => $variations, 'medias' => $medias, 'cover_image' => $image ? 'image-' . $image : '', 'url' => get_permalink($product->get_id())]; }
    private function specs(WC_Product $product): array { $specs = []; foreach ($product->get_attributes() as $attribute) { if (!$attribute instanceof WC_Product_Attribute) continue; $values = $attribute->is_taxonomy() ? wc_get_product_terms($product->get_id(), $attribute->get_name(), ['fields' => 'names']) : $attribute->get_options(); $values = array_values(array_filter(array_map('strval', $values), 'strlen')); if ($values) $specs[] = ['name' => wc_attribute_label($attribute->get_name()), 'value' => $values]; } return $specs; }
    private function variation_specs(WC_Product_Variation $variation): array { $specs = []; foreach ($variation->get_attributes() as $name => $value) { if ($value === '') continue; $taxonomy = str_replace('attribute_', '', $name); $term = taxonomy_exists($taxonomy) ? get_term_by('slug', $value, $taxonomy) : false; $specs[] = ['name' => wc_attribute_label($taxonomy), 'value' => $term ? $term->name : (string) $value]; } return $specs; }
    private function category(WC_Product $product): array { $terms = wp_get_post_terms($product->get_id(), 'product_cat'); usort($terms, static fn($a, $b) => $b->parent <=> $a->parent); return $terms ? ['code' => $terms[0]->slug, 'name' => $terms[0]->name] : ['code' => '', 'name' => '']; }
    private function brand(WC_Product $product): string { foreach (['product_brand', 'pwb-brand', 'pa_brand', 'brand'] as $taxonomy) if (taxonomy_exists($taxonomy)) { $brands = wc_get_product_terms($product->get_id(), $taxonomy, ['fields' => 'names']); if ($brands) return (string) $brands[0]; } return ''; }
    private function active(WC_Product $product): bool { return $product->get_status() === 'publish' && $product->get_catalog_visibility() !== 'hidden'; }
}
